base_model: answerdotai/ModernBERT-base
training:
  task: sbert
  sbert:
    dataset_name: "erickfmm/agentlans__multilingual-sentences__paired_10_sts"
    output_dir: "./output/es_sbert_modernbert_mean"
    batch_size: 16
    epochs: 4
    warmup_steps: 1200
    evaluation_steps: 5000
    learning_rate: 2e-5
    max_train_samples: 500000
    max_eval_samples: 10000
    max_seq_length: 8192
    pooling_mode: mean
    trust_remote_code: false
    use_amp: true
    resample_balanced: true
    resample_std: 0.3
