base_model: bertin-project/bertin-roberta-base-spanish
training:
  task: sbert
  sbert:
    dataset_name: "erickfmm/agentlans__multilingual-sentences__paired_10_sts"
    output_dir: "./output/es_sbert_bertin_cls"
    batch_size: 12
    epochs: 4
    warmup_steps: 800
    evaluation_steps: 4000
    learning_rate: 2e-5
    max_train_samples: 500000
    max_eval_samples: 10000
    max_seq_length: 512
    pooling_mode: cls
    trust_remote_code: false
    use_amp: false
    resample_balanced: true
    resample_std: 0.3
